-- MySQL Script generated by MySQL Workbench
-- Mon Apr 21 17:29:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UniveristyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UniveristyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniveristyDB` DEFAULT CHARACTER SET utf8 ;
USE `UniversityDB` ;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversityDB`.`Department` ;

CREATE TABLE IF NOT EXISTS `UniversityDB`.`Department` (
  `D_ID` INT NOT NULL,
  `D_Name` VARCHAR(45) NULL,
  `Office_Loc` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  PRIMARY KEY (`D_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityDB`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversityDB`.`Course` ;

CREATE TABLE IF NOT EXISTS `UniversityDB`.`Course` (
  `C_ID` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `Credits` VARCHAR(45) NULL,
  `Schedule` VARCHAR(45) NULL,
  `D_ID` INT NULL,
  PRIMARY KEY (`C_ID`),
  CONSTRAINT `Course_DID_FK`
    FOREIGN KEY (D_ID)
    REFERENCES `UniversityDB`.`Department` (D_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityDB`.`INSTRUCTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversityDB`.`INSTRUCTOR` ;

CREATE TABLE IF NOT EXISTS `UniversityDB`.`INSTRUCTOR` (
  `I_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `HIREDATE` VARCHAR(45) NULL,
  `D_ID` INT NULL,
  PRIMARY KEY (`I_ID`),
  CONSTRAINT `INSTR_ID_FK`
    FOREIGN KEY (D_ID)
    REFERENCES `UniversityDB`.`Department` (D_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityDB`.`STUDENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversityDB`.`STUDENT` ;

CREATE TABLE IF NOT EXISTS `UniversityDB`.`STUDENT` (
  `S_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `DOB` VARCHAR(45) NULL,
  `MAJOR` VARCHAR(45) NULL,
  `ADVISOR_ID` INT NULL,
  PRIMARY KEY (`S_ID`),
  CONSTRAINT `STUD_ID_FK`
    FOREIGN KEY (ADVISOR_ID)
    REFERENCES `UniversityDB`.`INSTRUCTOR` (I_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityDB`.`Enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UniversityDB`.`Enrollment` ;

CREATE TABLE IF NOT EXISTS `UniversityDB`.`Enrollment` (
  `E_id` INT NOT NULL,
  `S_id` INT NULL,
  `C_id` INT NULL,
  `Semester` VARCHAR(45) NULL,
  `Year` INT NULL,
  PRIMARY KEY (`E_id`),
  CONSTRAINT `ENROLL_SID_FK`
    FOREIGN KEY (S_id)
    REFERENCES `UniversityDB`.`STUDENT` (S_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ENROLL_CID_FK`
    FOREIGN KEY (C_id)
    REFERENCES `UniversityDB`.`Course` (C_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
